### ISSUE TITLE
CakePHP 3.0

### ISSUE THREAD

**Issue by marksie1988** [jvalecillos/cakephp-yalp#1]
Will this work with CakePHP 3.0 or are there plans to make it?

**Comment by jvalecillos** [comment]
I haven't tried it on CakePHP 3.0. I suppose some changes would be needed regarding AuthComponent and PSR-4 in 3.0.

**Comment by LDSign** [comment]
Any progress in making this compatible with 3.0?

**Comment by jkimilu** [comment]
possible to use this with cakephp3x?
