### ISSUE TITLE
User table?

### ISSUE THREAD

**Issue by iamdriz** [jvalecillos/cakephp-yalp#2]
Maybe I have missed this. But why do you need a user table? Isn't the list of users stored on the server you are using for the LDAP? I was under the impression you could allow access to your application using the list of users in your open directory... Or is this not the case? Or have I missed something whereby you need to copy across your users to your DB as well.

**Comment by iamdriz** [comment]
Also reading through the logic it mentions about creating the user if it's not found in the user table but is found on the ldap server.. But I don't see anywhere where it actually adds the user.

**Comment by jvalecillos** [comment]
The User table is used to keep CakePHP ACL compatibility (Access Control List). Users are supposed to be imported to access the application in first place.

**Comment by iamdriz** [comment]
What's that comment in your code about adding the record if the user can't be found?

**Comment by jvalecillos** [comment]
You are referring to a comment about creating a new db entry in case the user is not found in the DB, right?. Originally, the users were created in the database on first login, but it was changed in favor of user importation. When importing users you can assign them to groups based on ACL rules.

**Comment by iamdriz** [comment]
So you need to have a carbon-copy of the users on the LDAP server on the Web server where your CakePHP application is installed. And then whenever a user logs onto your application it both authenticates in CakePHP AND also on the LDAP server. Is that correct?

**Comment by jvalecillos** [comment]
Yes. That's correct. That way you can assign roles to users. Keep in mind that the real authentication is only against LDAP, the library only check the user existence in the database.
